// Code generated by protoc-gen-go.
// source: lorem.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	lorem.proto

It has these top-level messages:
	LoremRequest
	LoremResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoremRequest struct {
	RequestType string `protobuf:"bytes,1,opt,name=requestType" json:"requestType,omitempty"`
	Min         int32  `protobuf:"varint,2,opt,name=min" json:"min,omitempty"`
	Max         int32  `protobuf:"varint,3,opt,name=max" json:"max,omitempty"`
}

func (m *LoremRequest) Reset()                    { *m = LoremRequest{} }
func (m *LoremRequest) String() string            { return proto.CompactTextString(m) }
func (*LoremRequest) ProtoMessage()               {}
func (*LoremRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoremRequest) GetRequestType() string {
	if m != nil {
		return m.RequestType
	}
	return ""
}

func (m *LoremRequest) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *LoremRequest) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

type LoremResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Err     string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *LoremResponse) Reset()                    { *m = LoremResponse{} }
func (m *LoremResponse) String() string            { return proto.CompactTextString(m) }
func (*LoremResponse) ProtoMessage()               {}
func (*LoremResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoremResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoremResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*LoremRequest)(nil), "pb.LoremRequest")
	proto.RegisterType((*LoremResponse)(nil), "pb.LoremResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Lorem service

type LoremClient interface {
	Word(ctx context.Context, in *LoremRequest, opts ...grpc.CallOption) (*LoremResponse, error)
	Sentence(ctx context.Context, in *LoremRequest, opts ...grpc.CallOption) (*LoremResponse, error)
	Paragraph(ctx context.Context, in *LoremRequest, opts ...grpc.CallOption) (*LoremResponse, error)
}

type loremClient struct {
	cc *grpc.ClientConn
}

func NewLoremClient(cc *grpc.ClientConn) LoremClient {
	return &loremClient{cc}
}

func (c *loremClient) Word(ctx context.Context, in *LoremRequest, opts ...grpc.CallOption) (*LoremResponse, error) {
	out := new(LoremResponse)
	err := grpc.Invoke(ctx, "/pb.Lorem/Word", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loremClient) Sentence(ctx context.Context, in *LoremRequest, opts ...grpc.CallOption) (*LoremResponse, error) {
	out := new(LoremResponse)
	err := grpc.Invoke(ctx, "/pb.Lorem/Sentence", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loremClient) Paragraph(ctx context.Context, in *LoremRequest, opts ...grpc.CallOption) (*LoremResponse, error) {
	out := new(LoremResponse)
	err := grpc.Invoke(ctx, "/pb.Lorem/Paragraph", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Lorem service

type LoremServer interface {
	Word(context.Context, *LoremRequest) (*LoremResponse, error)
	Sentence(context.Context, *LoremRequest) (*LoremResponse, error)
	Paragraph(context.Context, *LoremRequest) (*LoremResponse, error)
}

func RegisterLoremServer(s *grpc.Server, srv LoremServer) {
	s.RegisterService(&_Lorem_serviceDesc, srv)
}

func _Lorem_Word_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoremRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoremServer).Word(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Lorem/Word",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoremServer).Word(ctx, req.(*LoremRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lorem_Sentence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoremRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoremServer).Sentence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Lorem/Sentence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoremServer).Sentence(ctx, req.(*LoremRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lorem_Paragraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoremRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoremServer).Paragraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Lorem/Paragraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoremServer).Paragraph(ctx, req.(*LoremRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lorem_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Lorem",
	HandlerType: (*LoremServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Word",
			Handler:    _Lorem_Word_Handler,
		},
		{
			MethodName: "Sentence",
			Handler:    _Lorem_Sentence_Handler,
		},
		{
			MethodName: "Paragraph",
			Handler:    _Lorem_Paragraph_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lorem.proto",
}

func init() { proto.RegisterFile("lorem.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x2f, 0x4a,
	0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x0a, 0xe1, 0xe2, 0xf1,
	0x01, 0x09, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x29, 0x70, 0x71, 0x17, 0x41, 0x98,
	0x21, 0x95, 0x05, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0xc8, 0x42, 0x42, 0x02, 0x5c,
	0xcc, 0xb9, 0x99, 0x79, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x20, 0x26, 0x58, 0x24, 0xb1,
	0x42, 0x82, 0x19, 0x2a, 0x92, 0x58, 0xa1, 0x64, 0xcd, 0xc5, 0x0b, 0x35, 0xb5, 0xb8, 0x20, 0x3f,
	0xaf, 0x38, 0x55, 0x48, 0x82, 0x8b, 0x3d, 0x37, 0xb5, 0xb8, 0x38, 0x31, 0x1d, 0x66, 0x24, 0x8c,
	0x0b, 0xd2, 0x9c, 0x5a, 0x54, 0x04, 0x36, 0x8e, 0x33, 0x08, 0xc4, 0x34, 0x9a, 0xcb, 0xc8, 0xc5,
	0x0a, 0xd6, 0x2d, 0xa4, 0xcb, 0xc5, 0x12, 0x9e, 0x5f, 0x94, 0x22, 0x24, 0xa0, 0x57, 0x90, 0xa4,
	0x87, 0xec, 0x4c, 0x29, 0x41, 0x24, 0x11, 0x88, 0x15, 0x4a, 0x0c, 0x42, 0x86, 0x5c, 0x1c, 0xc1,
	0xa9, 0x79, 0x25, 0xa9, 0x79, 0xc9, 0xa9, 0xc4, 0x6a, 0x31, 0xe2, 0xe2, 0x0c, 0x48, 0x2c, 0x4a,
	0x4c, 0x2f, 0x4a, 0x2c, 0xc8, 0x20, 0x52, 0x4f, 0x12, 0x1b, 0x38, 0xf4, 0x8c, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x75, 0x58, 0x61, 0xa4, 0x4c, 0x01, 0x00, 0x00,
}
